---
virtualmachines:
  - name: "rhel"
    image: "satellite-server-rhdp-6-17-06-13-25"
    packages: []
    memory: "32G"
    cores: 1
    image_size: "500G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
