---
virtualmachines:
  - name: "rhel"
    image: "docker://quay.io/myee/satellite:latest"
    image_type: registry
    packages: []
    memory: "32G"
    cores: 1
    image_size: "500G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
